### ISSUE TITLE
Open code in IDE from lab notes

### ISSUE THREAD

**Issue by dsyer** [eduk8s-labs/lab-spring-boot-k8s-getting-started#1]
Improved UX ideas: 

* click on button/link in lab notes and open existing file in IDE.
* click on snippet and add it to existing file (e.g. adding a `@GetMapping`)
* more complex things (e.g. adding a `@RestContoller` annotation to an existing class, and organizing imports)

**Comment by kdvolder** [comment]
Now that we have the first bullet point covered, we can move onto second one. I might also want to split this up into separate tickets. Especially the 3rd bullet point as it might be a lot more difficult / challenging to implement.

As to the second one:

> click on snippet and add it to existing file (e.g. adding a @GetMapping)

That probably isn't too hard to do. Most challening part of this is probably more in the 'desing' of it than the actual implementation. What I mean is... we have to think a little bit on how this ought to work from workshop author point of view. In particular... how can/should the workshop author indicate the location at which the snippet is to be inserted? The most obvious idea would be a specifying the exact line + column in the file. However, I fear this might be somewhat too fragile when the user might have already made some changes to the file. Then, the location infos in the workshop might not line up anymore and end up 'pasting' the snippet in the wrong place.

**Comment by kdvolder** [comment]
> click on button/link in lab notes and open existing file in IDE.

@dsyer I just merged this into master from: https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/pull/7#issue-443771892 so you can try it out. There's some example links at the top of 'intro.md'.

**Comment by dsyer** [comment]
The example seems to work, but not sure why it opens the Dockerfile on a random line. Would it be possible to specify the line number (and default to line 1)?

**Comment by kdvolder** [comment]
> opens the Dockerfile on a random line

It opens on the line number `5` as specified in the 'render snippet in markdown:

```
{% render "code-server/open-file-widget.liquid", file: "/home/eduk8s/Dockerfile", lineno: 5 %}
                                                                                         ^^^zero-based line number
```

... mind you the line number is 'zero based', same as vscode API. Perhaps the 'zero-based' index is what made it look 'random' (line number 6 instead of 5?). Or is it really not working at all? 

Note: ofcourse we could just substract 1 from the parameter being passed into our vscode extension if that seems more logical.

**Comment by kdvolder** [comment]
I update our extension so that line nrs now starts at 1: https://github.com/eduk8s/eduk8s-vscode-helper/commit/10fbb8b30aa2c5d1445f5d9daadcf8aab5713ea9

Tested it a bit on our own eduk8s cluster and seems to work.

**Comment by kdvolder** [comment]
The second bullet point:

- click on snippet and add it to existing file (e.g. adding a @GetMapping)

... is also implemented. Works on our (tools team) cluster, and I've merged this into master of this sample. So it should show up on main eduk8s instance as well in due course (I still don't fully understand how this 'pipeline' that makes it show up actually works, so not sure how / when it will show up. Might need someone to kick something to flush out stale sessions, portals, pods or what have you. 

In the mean time, can try it here: http://lab-spring-boot-k8s-gs-ui.training.eduk8s.springapps.io/workshops/catalog/

The way it works (from workshop author point of view) is as in this example:
https://raw.githubusercontent.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/master/workshop/content/intro.md

You create a `<pre>` element and put the pastable text inside. The functionality also needs two additional bits of info to be able to function.

- what file to paste into. This Indicated by adding a attribute `data-file` to the `<pre>` tag.
- whereabout in the file to paste. This is indicated by adding a `data-prefix`attribute.

Example:

```
<pre class="pastable" data-file="/home/eduk8s/Dockerfile" data-prefix="COPY --from">
# Multiple lines
# of stuff
# to paste
</pre>
```

When user clicks this... the text will be pasted into the Dockerfile right after the first line of text in that file that contains `COPY --from`.



The prefix is a string that the paste function will look for in the file. If it finds the string, then the text will be pasted on the following line. If string is not found, paste text is appended to end of the file instead.

**Comment by kdvolder** [comment]
For the time being I propose we do not explore into more complex stuff (organize imports is not obvious how it can be done, vscode itself doesn't understand java, so... it is a bit hard to do this).

**Comment by dsyer** [comment]
VSCode has a keyboard shortcut for “organize imports” so what do you mean when you say it doesn’t understand it? Surely we could ping that if we can ping the initializer wizard?

**Comment by kdvolder** [comment]
> what do you mean when you say it doesn’t understand it?

The vscode-extension has access to vscode-api. Vscode itself doesn't know anything about Java, there is another vscode-extension that does. But there's no easy way/principled api for one extension to talk to another. 

If we really really want to, I'm sure we can figure something out, but it could be very complex to hack up something like that. It depends a bit though, maybe it is as easy as finding a suitable 'command' regsirered by Java extension and trigger its execution somehow.

**Comment by kdvolder** [comment]
> VSCode has a keyboard shortcut for “organize imports” 

Actually, that's a good point, I think it means there's a 'command' for orgnize imports. It's not 'part of vscode' but its a command registered by the java extension. However, vscode does have api to execute commands, so that would probably work.

**Comment by kdvolder** [comment]
Earlier today in Zoom we discussed that it would be nice to specifically support some strategy for 'autopasting' yaml snippets. I imagine something where the desired location of the snippet would be given by a 'access path expression'. Something like like `spec.template.containers[0]` could be used to point a specific node in the yaml structure. This node can then be used as a 'reference' point to insert new text into the node as a 'child' or after of before the node as a 'sibling'. Details to be worked out.

A typescript/javascript library to parse yaml into a AST that carries position information will probably be needed to implement this. This looks like a good candidate: https://eemeli.org/yaml/#yaml

**Comment by kdvolder** [comment]
@dsyer There is now a first attempt at a 'yaml specific' paste in editor. I saw that you cleaned house a bit in the 'intro.md' so rather than polute this again with our IDE experimental cruft... I've placed our examples in separate markdown file now: https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/blob/master/workshop/content/playground.md

To sumarize: you can create a 'yaml auto paste' section like so:

```
<pre class="pastable" data-file="/tmp/deploy.yml" data-yaml-path="spec.template.spec.containers">
- name: another-container
  image: blah
  ports:
  - containerPort: 6677
</pre>
```

Works similar to other auto-paste snippets, but this one points to a location in a existng yaml file via a path of property names separated by `.`. You can also use `[<integer>]` to point at a element of a sequence. The paste snippet will be indented automatically to align with the existing children of the node pointed at and will be pasted at the beginning of that node. 
I could also imagine variants where the paste snippet is appended at the end instead or maybe as a sibling after or before the 'target' node, but that is not implemented at the moment.

**Comment by kdvolder** [comment]
@dsyer If you have chance to try out the yaml path 'auto paste'... feedback is welcome. Especially as currently only implemented one of several potential variants (i.e insert at start of node pointed at, where alternatives could be 'at-start' / ''at-end' / 'before' / 'after'. So curious to know if the current variant is good enough, or if we should implement all or some of the other variants as well.

**Comment by dsyer** [comment]
Looks good. I think we might eventually need a "replace-node" as well as an "insert-at-start-of-node". But this is great for now. Thanks.
