### ISSUE TITLE
k8s deployment fails with `allocated memory is greater than 256M available for allocation`

### ISSUE THREAD

**Issue by jldec** [eduk8s-labs/lab-spring-boot-k8s-getting-started#5]
The `small` session budget configures limitranger defaults for containers to 256MB memory, which is too small. Deployments fails with the following error:

```
allocated memory is greater than 256M available for allocation: -XX:MaxDirectMemorySize=10M, -XX:MaxMetaspaceSize=94141K, -XX:ReservedCodeCacheSize=240M, -Xss1M x 250 threads
```

I suggest tuning this to 1024MB in the [workshop.yaml](https://github.com/eduk8s-tests/lab-spring-boot-k8s-getting-started/blob/master/resources/workshop.yaml), or figuring out a way to set explicit (higher) limits in the deployment container spec.

see
https://docs.eduk8s.io/en/latest/runtime-environment/workshop-definition.html#resource-budget-for-namespaces

**Comment by trisberg** [comment]
there was a recent change in the buildpacks to fail the app if there isn't enough memory available based on the memory calculator. 768Mi should be enough for most Boot apps.

**Comment by dsyer** [comment]
We bumped the lab to "large".
