### ISSUE TITLE
Browser dev console errors when running workshop 

### ISSUE THREAD

**Issue by jldec** [eduk8s-labs/lab-spring-boot-k8s-getting-started#8]
Launched Spring Boot lab from https://hub.prod.eduk8s.io/   
I noticed errors in the (Firefox) dev console when I clicked on the link which triggers the Spring Initializr extension in VS Code. 

![Screenshot 2020-08-04 at 18 18 53](https://user-images.githubusercontent.com/849592/89324456-36fd9300-d67f-11ea-95d6-15f15a84e03c.png)

**Comment by jldec** [comment]
Clicking on the link to " open up the main application class " results in more errors.

![Screenshot 2020-08-04 at 18 30 42](https://user-images.githubusercontent.com/849592/89325519-d2433800-d680-11ea-945b-689821de0d7e.png)

**Comment by BoykoAlex** [comment]
Looks like @kdvolder and I addressed issues above with 97d8738377927dc911feb247ddae3e092bdf5cc4 and commits to **eduk8s-vscode-helper** repo

**Comment by kdvolder** [comment]
Closing this. @jldec Please raise new issue if you see more errors that should be addressed.
